CREATE TABLE IF NOT EXISTS SchemaMigrationsLock (
    id INT PRIMARY KEY,
    is_locked BOOLEAN NOT NULL DEFAULT FALSE,
    locked_at TIMESTAMP NULL DEFAULT NULL,
    locked_by VARCHAR(100) NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
