CREATE TABLE IF NOT EXISTS TmCase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    case_id VARCHAR(100) NOT NULL UNIQUE,
    platform VARCHAR(50) NOT NULL DEFAULT 'rewards',
    title VARCHAR(255) NOT NULL DEFAULT '',
    area VARCHAR(100) NOT NULL DEFAULT '',
    test_type VARCHAR(20) NOT NULL DEFAULT 'api',
    source_path VARCHAR(255) NOT NULL DEFAULT '',
    source_symbol VARCHAR(255) NOT NULL DEFAULT '',
    is_skipped BOOLEAN NOT NULL DEFAULT FALSE,
    id_status VARCHAR(20) NOT NULL DEFAULT 'unique',
    substring_unsafe BOOLEAN NOT NULL DEFAULT FALSE,
    steps TEXT NULL,
    business_rule TEXT NULL,
    expected_result TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    version INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NOT NULL DEFAULT 'system',
    updated_by VARCHAR(100) NOT NULL DEFAULT 'system',
    INDEX idx_tm_case_area (area),
    INDEX idx_tm_case_status (status),
    INDEX idx_tm_case_platform (platform),
    INDEX idx_tm_case_id_status (id_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
